---
output: md_document
params:
  title: a title
  conds: default fill me in
---

<!----
Template takes..
conds:  conditions to use (done using mustache syntax)
--->

`r params$title`
===========================

```{r}
library(knitr)
opts_knit$set(self.contained=TRUE, root.dir="../")
opts_chunk$set(fig.cap="", error=TRUE, cache=FALSE, echo=FALSE, fig.width=5, fig.height=3.5)
```

```{r, message=FALSE}
#setup
source('scripts/eta_squared.R')
library(reshape)
library(plyr)
library(ggplot2)
source('scripts/helper.R')

scored.dat = subset(read.csv('data/1_scored.csv', colClasses = c(Subject='factor')), 
                    task %in% params$conds)

dvs = c('ACC.ser', 'ACC.item', 'ACC.order')
```

Descriptives
----

#### N
```{r}
ddply(scored.dat, .(task, trialtype), plyr:::summarize, Participants = length(task))
```

Residual Check
----
#### Scatterplots of Similar vs Dissimilar
```{r}
y_lim = ylim(c(0,1))

mdat = melt(scored.dat, id.vars=c('Subject', 'task', 'trialtype'), measure.vars=dvs)
cdat = cast(mdat, task + Subject + variable ~ trialtype)
qplot(D, S, data=cdat, facets=variable ~ task) + y_lim  + geom_smooth(method=lm, se=FALSE) + geom_abline(intercept=0, slope=1, color='gray', linetype=1)                                                                                                 
```

gray line has intercept=0, slope=1. Blue line is regression fit.

#### Averaged across similarity conditions (and z-scored)
```{r}
outliers = function(df){
  z = scale(df$y)
  df[abs(z) > 3,]
}


cdat$avg = with(cdat, (D + S) / 2)
p = qplot(task, avg, data=cdat, facets=variable ~ ., position=position_jitter(width=.025, height=0), alpha=.5) + 
    stat_summary(fun.data='mean_cl_boot', color='red')
p %+% ddply(cdat, .(task, variable), transform, avg = scale(avg))
```


Effect Plots
----

Standard errors are between group

```{r, cache=FALSE}
y_labels = c(ACC.ser = 'Serial Recall', ACC.item = 'Item Recall', ACC.order = 'Order Accuracy')
trialtype_labels = c(S = 'Similar', D = 'Dissimilar')
scale_args = list("Trial Type", breaks = c('S', 'D'), labels = c('Similar', 'Dissimilar'))

# Experiment specific plotting components
xlabel = 'Task'
for (task in names(xlabels)){
    # xlabels comes from helper.R TODO: reduce speghetti string..
    if (task %in% scored.dat$task) xlabel = xlabels[task]
}

scored.dat$trialtype = relevel(scored.dat$trialtype, ref='S')
scored.dat$task = revalue(scored.dat$task, pub_conds)  # pub_conds comes from helper.R

if (350 %in% scored.dat$task){
  poolsize = as.character(c(10, 15, 30, 60, 350))
  scored.dat$task = factor(scored.dat$task, poolsize)
}

# Plots
all_plots = list()
for (dv in dvs){
  meanse = ddply(scored.dat, .(task, trialtype), function(df) ps.meanse(df[,dv]))
  p.fx = p.summary %+% meanse + 
    do.call(scale_color_manual, c(scale_args, list(values=c("#377eb8", "#e41a1c")))) +
    do.call(scale_shape_manual, c(scale_args, list(values=c(1, 2)))) +
    labs(y=y_labels[dv], x=xlabel)
  print(p.fx)
  all_plots[[dv]] = p.fx
}
save(all_plots, file=paste0('summary/', scored.dat$folder[1], '_plots', '.Rdata'))
```

```{r, results='asis'}
print.block = function(obj){
  cat('\n```\n')
  print(obj)
  cat('\n```\n')
}
scored.dat$Unique_ID = paste(scored.dat$Subject, scored.dat$task)
for (dv in dvs){
  cat('\n\n')
  cat(paste0('\n\n',dv,'\n----\n\n'))
  formula = as.formula(paste(dv, " ~ task * trialtype + Error(Unique_ID/trialtype)"))
  fit = aov(formula, data=scored.dat)
  
  print.block(summary(fit))
  
  cat('\n#### Partial Eta-square\n\n')
  print.block(eta.2(fit, ret.labels=TRUE))
  
  cat('\n\n#### Simple Effects\n\n')

  formula.simple = as.formula(paste(dv, " ~ trialtype + Error(Unique_ID/trialtype)"))
  fit.simple = d_ply(scored.dat, .(task), function(df){
    task = unique(df$task)
    cat(paste0('\n\n#### ', task, '\n'))
    simple.fx = aov(formula.simple, data=df)
    print.block(summary(simple.fx))
    print.block(eta.2(simple.fx, ret.labels=TRUE))
  })
  
  
  
  #simple.fx = dlply(scored.dat, .(task), function(df){
  #  tmp_df = cast(df, task + Subject ~ trialtype, value=dv)
  #  t.test(tmp_df$S, tmp_df$D, paired=TRUE)
  #})
  #print(simple.fx[])
}
```
