site_name: Phonological Similarity in Complex Span
theme: 'readthedocs'
theme_dir: 'theme_tweak'
docs_dir: '.'
pages:
    - Home: 'index.md'
    - Experiments:
        - 'E1 (ospan)': 'exps/e1.md'
        - 'E2 (shuffled)': 'exps/e2.md'
        - 'E3 (pooled)': 'exps/e3.md'
        - 'E4 (names)': 'exps/e4.md'
    - 'Multilevel Models':
        - 'Serial Accuracy': 'mlm/ACC.ser.md'
        - 'Item Accuracy':   'mlm/ACC.item.md'
        - 'Order Accuracy':  'mlm/ACC.order.md'
